### PR TITLE
Add Chinese translations for YuzuTalk.

### PR DESCRIPTION
**Pull request by wangyw15**
Add Chinese translations for YuzuTalk.

Translated strings will be edited later when mistranslation is found or international client of Blue Archive released.

### CODE REVIEW

**Comment by wangyw15** [comment]
In ISO 639-1, there is only one language code for Chinese (zh). Currently, the translation is only for Chinese Traditional. Is it possible to use "cn" as the code for Chinese Simplified?

**Comment by YuzuTalk** [comment]
Thank you for your cooperation in translation!

Select the language to display from the language selected in the YuzuTalk or the language using in the browser.
https://developer.mozilla.org/en/docs/Web/API/Navigator/language
I'm thinking of using this region code to distinguish between Traditional and Simplified Chinese.

**Comment by wangyw15** [comment]
Thank you for your reply.

So instead of using only "zh" to represent Chinese, "zh-CN" and "zh-TW" would be used for two variants?
If so, later I would translate the text into two variants.

**Comment by YuzuTalk** [comment]
Proposed Thank you!

I just checked and there are other regions besides zh-TW that use traditional Chinese characters.
So, why not use "zh-hant" and "zh-hans" in the JSON file for translation, and separate them according to the value of window.navigator.language in the code?
```js
let code = window.navigator.language;
switch (locale) {
 case "zh-TW":
 case "zh-HK":
 code = "zh-hant";
 break;

 case "zh-CN":
 code = "zh-hans";
 break;

 default:
 break;
}
```
Like this!

**Comment by wangyw15** [comment]
Thank you for your reply.

When I type `window.navigator.language` in the console, it returns codes like "zh-CN", "zh-TW". "zh-Hans" and "zh-Hant" are the best choices, but the browser normally returns codes like "zh-CN". So, if you support automatically convert theses codes, it would be great.
I added some to better cover other regions.
```javascript
let code = window.navigator.language;
switch (locale) {
 case "zh-TW":
 case "zh-HK":
 case "zh-MO":
 code = "zh-hant";
 break;

 case "zh-CN":
 case "zh-SG":
 code = "zh-hans";
 break;

 default:
 break;
}
```

**Pull request merged**
