### PR TITLE
Add Chinese Simplified translations for YuzuTalk

### PR DESCRIPTION
**Pull request by wangyw15**
Add Chinese Simplified translations for YuzuTalk.

Translated strings will be edited later when mistranslation is found or international client of Blue Archive released.

### CODE REVIEW

**Comment by YuzuTalk** [comment]
Thank you for adding Simplified Chinese!

We will add a function to convert the locale according to the language used in the browser. 
After that, we will reflect the translation, so please wait until then.

**Comment by wangyw15** [comment]
Sorry for disturbing you so late, but can you change my name to `wangyw15` on the [YuzuTalk Website](https://yuzutalk.net/). It's kind of strange to display such a long name (also my full name) in the list. 
If it bothers, keeping the name unchanged is OK. 😂

**Comment by YuzuTalk** [comment]
OK!
I fixed the repository, but it seems that it will take some time to be reflected because vercel is crashing.
Please wait until the server is fixed!

**Comment by wangyw15** [comment]
Thank you!!!

**Pull request merged**
